LB1/myblog/blog/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('', views.PostView.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments')]

LB1/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

LB1/myblog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField('Текст запису')
    author = models.CharField('Автор', max_length=100)
    date = models.DateField('Дата публікації')
    img = models.ImageField('Зображення', upload_to='image')

    def __str__(self): #красивое отображение заголовок+текст+автор списком
        return self.title
    

    class Meta:                     #исп.для определения разл вещей наследоваться      другими классами(бд, разрешение, од\множ число)
      verbose_name = 'Запис' #исп для определения удобочитаемого единств имени модели, заменяет стандарт согл об именах джанго
      verbose_name_plural = 'Записи'

class Comments(models.Model):
   email=models.EmailField()
   name=models.CharField('Нікнейм', max_length=50)
   text_comments=models.TextField('Текст коментарія', max_length=1000)
   post=models.ForeignKey(Post, verbose_name='Публікації', on_delete=models.CASCADE)
   def __str__(self):
        return f'{self.name}, {self.post}'
    
   class Meta:
      verbose_name = 'Коментарій'
      verbose_name_plural ='Коментарії'

LB1/myblog/blog/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views.generic.base import View #род класс, на базе которого будут создаваться представления
from .models import Post
from .form import CommentsForm

class PostView(View):
    '''Вивод записів'''
    def get(self,request):
        posts = Post.objects.all()  #ссылка на всю инфу из таблы, постлист - имя, по которому обращаемся к данным, которые взяли
        return render(request, 'blog/blog.html', {'post_list':posts})  # render объединяет шаблон и данные из модели+возвращает объект


class PostDetail(View):
    '''Окрема сторінка записів'''
    def get(self, request, pk): #pk = id post number
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post':post})

class AddComments(View):
    '''Додавання коментарів'''
    def post(self, request,pk):
        form = CommentsForm(request.POST)#все данные от пользователя
        if form.is_valid():#валидно ли?
            form = form.save(commit=False)#сохр в бд если хорошо, ф. приостановляет сохр для редакт данных и доб новых
            form.post_id = pk
            form.save()#сохр все данные в бд
        return redirect(f'/{pk}')

LB1/myblog/templates/blog/blog.html
{% load static %}
<html>
  <head>
    <title>Мой блог</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />

    <link rel="shortcut icon" href="css/images/favicon.ico" />
  </head>
  <body>
    <div class="shell">
      <div class="border">
        <div id="navigation">
          <ul>
            <li><a href="/" class="active">Головна</a></li>
            <li><a href="/admin">Адмін панель</a></li>
          </ul>
        </div>

        <div id="main">
          <div id="content" class="left">
            <div class="projects">
              <h3>Записи</h3>
              {% for post in post_list %}
              <div class="item">
                <div class="image left">
                  <img src="{{ post.img.url }}" width="200px" />
                </div>
                <div class="text left">
                  <h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
                  <p>{{ post.description }}</p>
                  <p>Автор: {{ post.author }}</p>
                </div>
                <div class="cl"></div>
              </div>
              {% endfor %}
            </div>
          </div>

          <div class="cl"></div>
        </div>
      </div>

      <div id="footer">
        <p class="copy right">Copyright &copy; 2022</p>
      </div>
    </div>
  </body>
</html>

LB1/myblog/templates/blog/blog_detail.html
{% load static %}
<html>
  <head>
    <title>Мой блог</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />

    <link rel="shortcut icon" href="css/images/favicon.ico" />
  </head>
  <body>
    <div class="shell">
      <div class="border">
        <div id="navigation">
          <ul>
            <li><a href="/" class="active">Головна</a></li>
            <li><a href="/admin">Адмін панель</a></li>
          </ul>
        </div>

        <div id="main">
          <div id="content" class="left">
            <div class="projects">
              <h3>{{ post.title }}</h3>
              <p align="center">
                <img src="{{ post.img.url }}" width="50%" />
              </p>
              <div class="item">
                <div class="text left">
                  <p>{{ post.description }}</p>
                  <p>Автор: {{ post.author }}</p>
                </div>
                <div class="cl"></div>
              </div>
            </div>
          </div>
          <div class="form-comment">
            <h3>Залишити коментар</h3>
            <div>
              <form action="{%url 'add_comments' post.id%}" method="post">
                {% csrf_token %}
                <label>Ваш коментар</label>
                <textarea name="text_comments"></textarea>
                <label>Ваш нікнейм</label>
                <input type="text" name="name" />
                <label>Ваш email</label>
                <input type="email" name="email" />
                <input type="submit" />
              </form>
            </div>
          </div>
          <div>
            {%for comment in post.comments_set.all%}
            <div class="view-comment">
              <h4>{{comment.name}}</h4>
              <p>{{comment.text_comments}}</p>
            </div>
            {%endfor%}
          </div>
          <div class="cl"></div>
        </div>
      </div>

      <div id="footer">
        <p class="copy right">Copyright &copy; 2022</p>
      </div>
    </div>
  </body>
</html>